---
# title: ""
# listing:
#   contents: papers
#   type: default
#   sort: "date desc"
#   fields: [image, title, description] #author, description date, 
#   field-display-names:
#     date: "Last updated"
#   max-description-length: 175
#   image-align: left
format:
  html:
    link-external-icon: false
sidebar: true
toc: false 
search: true
callout-appearance: simple
callout-icon: false
linkcolor: "#0F4D92"
---

### Working papers

#### [Place-based Policy, Migration Barriers, and Spatial Inequality](papers/Huynh_Nghiem_JMP.pdf){target="_blank"} \[JMP\]

::: {.callout-caution collapse="false"}
## Abstract

This paper quantifies the effects of place-based tax incentives and migration barrier reductions on spatial inequality in Vietnam. I develop a dynamic spatial general equilibrium model that captures the interactions between geography, policy measures, occupational choices, migration, congestion, and agglomeration effects. Using firm and household data spanning two decades, combined with multiple difference-in-differences approaches, I identify key factors governing policy effects: the firm entry elasticity and policy-related changes in migration costs. The findings suggest that place-based tax incentives can effectively diminish spatial inequality, especially when coupled with robust public services. Easing migration barriers to more affluent areas, while reducing inequality, can also decrease welfare in these cities. A balanced approach that employs place-based incentives to encourage firm establishment in less developed areas, alongside reduced migration barriers to more developed regions, is more effective than focusing solely on promoting development in underdeveloped areas.

[Full Paper (PDF)](papers/Huynh_Nghiem_JMP.pdf){target="_blank"}

<!-- #### Press Coverage -->

<!-- 1. [Title of Press Coverage 1](link-to-press-coverage-1) -->

<!-- 2. [Title of Press Coverage 2](link-to-press-coverage-2) -->

<!-- 3. [Title of Press Coverage 3](link-to-press-coverage-3) -->
:::



#### [Why Does the Sex Ratio at Birth Rise? Evidence from Vietnam](papers/Sex_ratio_vn.pdf){target="_blank"}

(with Ngoc T. Nguyen)

::: {.callout-caution collapse="true"}
## Abstract

This study connects Vietnam's elevated sex ratio at birth (SRB) to the 2001 US-Vietnam Bilateral Trade Agreement. Our model incorporates three major factors that influence SRB: income, relative returns based on the child's sex, and fertility. The model presents twelve predictions, which are tested using large-scale repeated cross-sectional and panel surveys in a difference-in-difference design. The results indicate that mothers who experience larger tariff reductions tend to have a stronger preference for sons, work more, and desire fewer children. These findings suggest that fertility is the main driver of the elevated SRB. Overall, this paper highlights the interplay between cultural norms, maternal income, childcare, and fertility, revealing the unexpected demographic impact of trade policies.

[Full Paper (PDF)](papers/Sex_ratio_vn.pdf){target="_blank"}

[SSRN](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4582123)

:::


