---
title: "Place‑based Policy, Migration Barriers, and Spatial Inequality"
authors: ""
date: 2025-06            
categories: ["Working paper"]
description: >
  
links:
  # - text: "PDF"
  #   icon: file-pdf
  #   href: Huynh_Nghiem_JMP.pdf
  # - text: "Slides"
  #   href: slides/huynh_spatial_ineq.pdf
  # - text: "Replication code"
  #   href: https://github.com/nqhuynh/spatial‑ineq
published-title: "Updated"  # This changes the label
date-format: "MM-YYYY"
status: "Revising" 
language: 
  title-block-author-single: "Co-authors"
format:
  html:
    # hide everything except the abstract when users land on the page itself
    code-fold: true
---

## Abstract

How should governments reduce spatial inequality—by attracting firms to disadvantaged regions or helping people reach thriving ones? This paper studies Vietnam's implementation of both policies, place-based tax incentives in 2003 and relaxation of the household registration system (Ho Khau) in 2005. I embed these shocks in a dynamic spatial general equilibrium model with firm life cycles and endogenous public services, estimating key elasticities from policy-induced variations. The combined policies raise aggregate welfare by 1.3% and reduce spatial inequality by 0.7%. Migration reform alone reduces spatial inequality three times more than tax incentives. However, the migration policy's impact depends critically on destination targeting: facilitating migration to the largest cities generates minimal redistribution, while reducing barriers to other destinations cuts spatial inequality by 1.3%, nearly double the combined policy effect. These findings suggest that strategic policy design matters more than choosing between place-based and people-based approaches.

::: {style="margin-bottom: 1rem; display: flex; gap: 10px;"}
<a href="Huynh_Nghiem_JMP.pdf" target="_blank" style="display: inline-block; padding: 2px 8px; border: 1px solid #ccc; text-decoration: none; font-size: 1rem; color: white; background-color: #841617; text-transform: uppercase;">PDF</a>

<a href="https://papers.ssrn.com/sol3/papers.cfm?abstract_id=5281304" target="_blank" style="display: inline-block; padding: 2px 8px; border: 1px solid #ccc; text-decoration: none; font-size: 1rem; color: white; background-color: #841617; text-transform: uppercase;">SSRN</a>
:::

